var applicationstrings = {
    EN: {
        'add': "Add",
        'code': "Code",
        'desc': "Desc.",
        'export': "Export",
        'noevents': "No future events.",
        'nodata': "No Data",
        'tasktypeerr': "Task type cannot be empty.",
        'taskdetails': "Task Details",
        'projectdetails': "Project Details",
        'taskno': "Task No",
        'taskdesc': "Task Description",
        'actdesc': "Act. Description",
        'taskdepartment': "Task Department",
        'description': "Description",
        'start': "Start",
        'end': "End",
        'quolines': "There must be lines to create quotation.",
        'status': "Status",
        'single': "Single User",
        'multiple': "Multiple Users",
        'followed': "Followed",
        'fillrequired': "Please fill the required fields",
        'newpurchaseorder': "New Purchase Order",
        'purchaseorderscannotbediff': "Purchase Orders cannot be different.",
        'newpurchaseorderrequisition': "New purchase order requisition.",
        'notvalid': "Please select valid value(s) for the highlighted field(s)",
        'selectanactivity': "Please select an activity to plan",
        'selectstatus': "Please select a status to continue",
        'dateerr1': "From date can not be greater than to date",
        'dateerrcontract' : "Start date cano not be greater than end date",
        'completed': "Completed",
        'waitingapproval': "Waiting Approval",
        'today': "Today",
        'chart1': "Task Ratio By Priority",
        'chart2': "Task Ratio By Status",
        'chart3': "Booked Hours By Month",
        'columnchooser': "Show/Hide Columns",
        'menu': "Menu",
        'newfolder': "New Folder",
        'newscreen': "New Screen",
        'newtab': "Open in new tab",
        'addnew': "Add New",
        'remove': "Remove",
        'reset': "Reset",
        'plannedtasks': "Planned Tasks",
        'unplannedtasks': "Unplanned Tasks",
        'multipleusers': "Multiple users assigned tasks cannot be moved on this screen",
        'commentsrequired': "Comments field can not be blank",
        'mapstartdayerr': "The start date can be up to 5 days in advance.",
        'audit': "Audit",
        'search': "Search",
        'history': "History",
        'selectall': "Select All",
        'allselected': "All Selected",
        'countSelected': "# of % selected.",
        'person': "Person",
        'recordcount': "Record Count",
        'listcount': "List Count",
        'follow': "Follow",
        'on': "ON",
        'off': "OFF",
        'map': "Map",
        'edit': "Edit",
        'chklistitemrate100': "Overall rate should be 100",
        'locked': " Locked",
        'notlocked': " Not Locked",
        'checklistlocked': "Checklist is locked!",
        'schfrom': "Sch. From",
        'schto': "Sch. To",
        'activity': "Activity",
        'startenderr': "End time can not be less than start time",
        'completeerr': "Completed date can not be less than request date",
        'ap': "Actual / Planned",
        'actual': "Actual",
        'planned': "Planned",
        'usercheck': "Please select at least a user to save",
        'newj09': "Please select at least 30 days in advance  for next",
        'newjconrequestmaterials':
        "You are requesting material(s) for a contractor. Received materials will be registered the back on LM.",
        'created': "Created",
        'createdby': "Created By",
        'selectarecord': "You must select a record before performing this action",
        'selectasystemtocreateuser': "Please select a system to create user",
        'comments': "Comments",
        'documents': "Documents",
        'customer': "Customer",
        'branch': "Branch",
        'download': "Download",
        'details': "Details",
        'filter': "Filter",
        'allday': "All Day",
        'checkall': "Check All",
        'frequencyzerovalue': "Frequency field value can not be zero",
        'autocreationzerovalue': "Auto creation time value can not be zero",
        'frequencyerr': "Upcoming task reminder cannot be greater than frequency",
        'trxtypecheck': "Please select transaction type first",
        'daterequested': "Date requested cannot be at the future",
        'deadline': "Deadline cannot be at the past",
        'boodate01': "Date cannot be at the future",
        'boodate02': "Date cannot be entered before requested date",
        'misccostdate': "Date cannot be entered before requested date",
        'pastdate': "Past date can not be selected",
        'pptasknotselected': "You must select at least a task record to continue",
        'invpspnotselected': "You must choose at least one progress payment which will be included in the invoice.",
        'invlinenotselected': "You must select at least a line to continue",
        'contractdelete': "You must select at least a line to continue",
        'potowarehousenotselected': "You must select at least a line to continue",
        'selectatask': "You must select a task record to continue",
        'save': "Save",
        'activitycompleted': "Selected activity is completed and cannot be moved",
        'misccostexch': "Exchange rate is not set for the selected date",
        'closedanddisabled': "Screen is disabled because of the record has been closed",
        'actdurationdatecontrol': "Activity start and end dates must be filled",
        'pswdcomplexity': "The password field does not meet the standards. The password must be at least 8 characters long and contain uppercase, lowercase, special character (!@#$%^&*.) and numbers.",
        'fileisbeingprepared': "Requested file is being processed, please wait for a while...",
        'ACTIVE': "Active",
        'COMPLETED': "Completed",
        'PAUSED': "Paused",
        'WAITING': "Waiting",
        'location': "Location",
        'pointcount': "Point Count",
        'continuing': "Continuing",
        'actcount': "Act. Count",
        'total': "Total",
        'totalcost': "Total Cost",
        'totalsales': "Total Sales",
        'totalpayment': "Total Payment",
        'lastaction': "Last Action",
        'showall': "Show All",
        'statuschange': "Status Change",
        'dayoffrequesttypeinfo': "Maximum time available for the selected type of leave: ",
        'chargingperiods': {
            'DAILY': "Daily",
            'HOURLY': "Hourly",
            'KM': "Kilometre"
        },
        'durationunit': {
            'DAY': "Day",
            'HOUR': "Hour",
            'PCE': "Piece",
            'SET': "Set"
        },
        'activitystatuses': {
            'CALBAS': "Started",
            'MSKBEK': "Customer Related Waiting",
            'NOTSTARTED': "Not Started",
            'CLSTAM': "Completed",
            'MUSERT': "Customer Delay",
            'IZNGVN': "Permission / Security",
            'EKPDGS': "Trade Change",
            'MSİBTM': "Overtime",
            'PRCBEK': "Part required",
            'KESIF': "Discovery completed"
        },
        'delete': "Delete",
        'list': "List",
        'uploadfileextensionerr': "Only .xlsx or .xls extension is allowed",
        'specifycancellationreason': "Please specify cancellation reason",
        'calcmethod': {
            'CONTRACT' : "CONTRACT",
            'PLANNEDPARTS': "QUOTATION",
            'CUSTOMERPRICES': "CUSTOMER",
            'PARTUNITSALESPRICE': "PART",
            'PROGRESSPAYMENT': "LATEST",
            'AVERAGE': "AVERAGE",
            'TASKPRICE': "TASK PRICE",
            'CUSTOMERPARTPRICES': "Contracts",
            'QUOTATION': "QUOTATION"
        },
        'timekeepingitemstatus': {
            'R': "Released",
            'WA': "Awaiting Approval",
            'APP': "Approved",
            'REJ': "Rejected"
        },
        'nottype': {
            "NEWCOMMENT": "Comments",
            "NEWDOC": "Documents",
            "NEWTASK": "Tasks",
            "NEWTODO": "Todo's"
        },
        'unspecifieddoctype': "Unspecified",
        'eqpcodelength': "Equipment Code Length must be {0} characters long.",
        'progresspaymentselectionerror': "The current status of all selected progress payment records should be the same.",
        'progresspaymentinvoiceoptionserror': "The current organization/customer of all selected progress payment records should be the same.",
        'taskselectionerror': "The current status of all selected task records should be the same.",
        'misccosts': "Miscellaneous Costs",
        'errinvoicedate': "Invoice record can not be created between the 25th and the last day of the month.",
        'subjectisempty': "Subject field can't be empty!",
        'contentisempty': "Content field can't be empty!",
        'toisempty': "To field can't be empty!",
        'invalidemail': "Invalid E-Mail address!",
        'record': "Record",
        'whasquotation': "Warning!<br/> Quotation exists!",
        'groupusers': "Group Users",
        'selecttradeoruser': "Please specify a trade or user(s)",
        'quotations': "Quotations",
        'supervisions': "Supervisions",
        'purchaseorders': "Purchase Orders",
        'purchaseorderrequisitions': "Purchase Order Requisitions",
        'quotationorder': "This quotation is ranked <span style=\"color: #fb8b8b;font-size: 3em;\">{1}</span>rd among {0} offers in the lowest cost ranking.Task / Activity: {2} / {3}",
        'newquotation': "New Quotation",
        'newsupervision': "New Supervision",
        'openlinkinnewwindow': "Open Link In New Window",
        'copytoclipboard': "Copy To Clipboard",
        'pleaseselect': "Please Select",
        'trxtype': "Please select a transaction type first",
        'selectapart': "Please select a part first",
        'selectawarehouse': "Please select a warehouse",
        'checklisttypes': {
            'YESNO': "Yes/No",
            'NUMERIC': "Numeric",
            'DATE': "Date",
            'FREETEXT': "Free Text",
            'LOOKUP': "Lookup",
            'CHECKBOX': "Checkbox",
            'BARCODE' : "Barcode"
        },
        'yes': "Yes",
        'no': "No",
        'uploaderr': "Upload has been finished with errors. Please have a look at to the error list.",
        'error': "Error",
        'tcknerr': "T. C. ID Number must be 11 digits.",
        'partorequiperr': "Please add a part or equipment to continue",
        'ignoreddayserr': "All days of the week cannot be selected",
        'invoicerequiredfieldserr': "Please do not leave the Invoice No and Invoice Date fields empty.",
        'invalidphone': "Invalid Phone Number",
        'erremptyrating': "Please choose a rating value",
        'addtoWarehouse': "Add to Warehouse",
        'addtoWarehouseasList': "Add All to Warehouse",
        'refundFromWarehouse': "Refund",
        'purchaseordererror': "The Input / Output Quantity cannot exceed the pending amount.",
        'typeleveleeror': "Update failed due to type difference.",
        'typetofilter': "Type to filter",
        'clearfilter': "Clear filter",
        'linedetails': "Line Details",
        'editprices': "Edit Prices",
        'sent': "Sent",
        'notsend': "Not Sended",
        'clickherefornewquo': "Click Here for Create New Quo.",
        'clickforseequo': "Click Here for Quotations",
        'sendforapproval': "Send For Approval",
        'alreadysent': "Sent For Approval",
        'completeactivity': "Complete / Hold",
        'alredycompleted': "Already Completed",
        'countmustbegreaterthenzero': "Count must be greater then 0",
        'countmustbegreaterthenzero2': "Count must be greater then 0",
        'pricemustbegreaterthenzero': "Price must be greater then 0",
        'discountmustbegreaterthenzero': "Price must be greater then 0",
        'deliverytowarehouse': "Delivery to Headquarters",
        'deliverytocrew': "Delivery to the Crew or Solution Partner",
        'deliverytocustomer': "Delivery to customer",
        'cannotupdateprice': "Cannot update this price type.",
        'sendback': "Send Back",
        'quototask': "Copy quotation to task",
        'returntotal': "Return Total",
        'invtotal': "Invoice Total",
        'returnhigherthanmax': "Return can not be higher than max value.",
        'gototask': "Goto Task",
        'gotoequipment': "Goto Equipment",
        'activitycomplete': "Activity Completed",
        'estimationcompleted': "Estimation Completed",
        'warehousescannotbedifferent': "Warehouses cannot be different.",
        'orgsscannotbedifferent': "Organizations Cannot be different.",
        'partmodalinfo': "<i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\" /> <strong>Contracted parts are listed by default. All records can be viewed by selecting \"All Parts\" from the filter options in the upper right.</strong>",
        'servicecodemodalinfo': "<i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\" /> <strong>Contracted service codes are listed by default. All records can be viewed by selecting \"All Service Codes\" from the filter options in the upper right.</strong>",
        'batchprogresstatus' : {
            "1" : "RUNNING",
            "2" : "SAVING",
            "3" : "COMPLETED"        
        },
        'customerselectionerr': "Customer or customer group should be specified.",
        'invalidlicenseplate': "Invalid License Plate",
        'invalidyear': "Invalid Year",
        'birthdateerr': "Birth date cannot be in the future",
        'licenseissuedateerr': "Driving license issue date cannot be in the future",
        'lastgraduateddateerr': "Last graduate date cannot be in the future",
        'invalidemail': "The E-Mail field contains an invalid value.",
        'details': "Details",
        'doccount': "Document Count",
        'invalidfiletype': "Invalid file type.",
        'warehouse': "Warehouse",
        'inventoryreceiptstatuses': {
            "N": "New",
            "WA": "Waiting Approval",
            "APP": "Approved",
            "RET" : "Returned"
        },
        'column': "Column",
        'columntitle': "Column Title",
        'tables': "Tables",
        'screenexists': "Screen Already Exists",
        'review': "Review",
        'seen': "Mark as seen",
        'adminguide': "Admin Guide",
        'enduserguide': "User Guide",
        'ok': "OK",
        'user': "User",
        'admin': "Admin",
        'fullscreen': "Full Screen",
        'guide': "Guide",
        'daterange': "Date Range",
        'setasprimary': "Set As Primary",
        'imgtyperequired': "Invalid file type. Please upload an image.",
        'contactinfo' : "Contact Info",
        'imgtyperequired': "Invalid file type. Please upload an image.",
        'createpo': "Create PO",
        'multiplewrhselected': "The Warehouses of the Selected Requests Must Be The Same.",
        'prqdetails': 'Purchase Order Requisition Details',
        'reqlinenotselected': "At least one line must be selected to be included in the purchase order.",
        'tsacompleted': "You cannot create an offer for a completed activity. Please contact your system administrator and create an offer on a new activity.",
        'cuspm': "Customer Project Manager",
        'regresp': "Region Responsible",
        'supplier': "Supplier",
        'address' : "Address",
        'signature': "Signature",
        'matchbyprovince': "Match By Province",
        'matchbycounty': "Match By County",
        'matchbycategory': "Match By Category",
        'matchbyregion': "Match By Region",
        'cusgetallinfo': "Do not mark for the 20 most costly progress payments to be received.",
        'similarrecordfound': "Attention! There is an open task of the same type and category for the relevant branch.",
        'selectpriorityfirst': "Please select the priority field first.",
        'setprofitmargin': "Set Profit Rate",
        'opentherecord': "Open The Record"

    },
    TR: {
        'add': "Ekle",
        'code': "Kod",
        'desc': "Tanım",
        'export': "Excel'e Al",
        'noevents': "Görev Bulunamadı.",
        'nodata': "Veri Bulunamadı",
        'taskdetails': "Görev Detayları",
        'projectdetails': "Proje Detayları",
        'taskno': "Görev No",
        'taskdesc': "Görev Tanımı",
        'actdesc': "Akt. Tanımı",
        'taskdepartment': "Görev Departmanı",
        'description': "Tanım",
        'start': "Başlangıç",
        'end': "Bitiş",
        'status': "Durum",
        'single': "Tek Kullanıcı",
        'multiple': "Çok Kullanıcı",
        'followed': "Takip Edilen",
        'fillrequired': "Lütfen zorunlu olarak işaretlenmiş alanları doldurunuz",
        'notvalid': "Lütfen işaretli alan(lar) için geçerli bir değer giriniz.",
        'selectanactivity': "Lütfen planlanacak bir aktivite seçiniz.",
        'dateerr1': "Başlangıç tarihi bitiş tarihinden sonra olamaz",
        'dateerr2': "Tarih aralığı geçersiz!",
        'dateerrcontract': "Sözleşme başlangıç tarihi bitiş tarihinden sonra olamaz",
        'tasktypeerr': "Görev türü boş olamaz.",
        'selectstatus': "Lütfen devam etmek için bir durum seçiniz",
        'completed': "Tamamlanmış",
        'waitingapproval': "Onay Bekleyen",
        'today': "Bügün",
        'chart1': "Öncelik Dağılımı",
        'chart2': "Durum Dağılımı",
        'chart3': "Aylara Göre Çal. Saatleri",
        'columnchooser': "Sütunları Gizle/Göster",
        'menu': "Menü",
        'newfolder': "Yeni Klasör",
        'newscreen': "Yeni Ekran",
        'newtab': "Yeni Sekmede Aç",
        'addnew': "Yeni Ekle",
        'remove': "Kaldır",
        'reset': "Temizle",
        'plannedtasks': "Planlanmış Görevler",
        'unplannedtasks': "Planlanmamış Görevler",
        'multipleusers': "Çoklu kullanıcı atanan görevler bu ekranda taşınamaz.",
        'commentsrequired': "Yorum alanı boş bırakılmamalıdır",
        'mapstartdayerr': "Başlangıç tarihi en erken 5 gün önce olabilir.",
        'audit': "Denetim",
        'search': "Ara",
        'history': "Tarihçe",
        'selectall': "Tümünü Seç",
        'allselected': "Tümü Seçildi",
        'countSelected': "#/% seçildi.",
        'person': "Kişi",
        'recordcount': "Kayıt Sayısı",
        'listcount': "Liste Sayısı",
        'follow': "Takip",
        'on': "Açık",
        'off': "Kapalı",
        'map': "Harita",
        'edit': "Düzenle",
        'chklistitemrate100': "Toplam oran 100 olmalıdır",
        'locked': " Kilitli",
        'notlocked': " Kilitli Değil",
        'checklistlocked': "Kontrol listesi kilitli!",
        'schfrom': "Baş. Tarihi",
        'schto': "Bit. Tarihi",
        'activity': "Aktivite",
        'startenderr': "Bitiş zamanı başlangıç zamanından önce olamaz",
        'completeerr': "Tamamlanma tarihi bildirim tarihinden önce olamaz!",
        'ap': "Gerçekleşen / Planlanan",
        'actual': "Gerçekleşen",
        'planned': "Planlanan",
        'usercheck': "Kaydetmek için en az bir kullanıcı seçiniz",
        'newj09': "Lütfen bir sonraki için en az 30 gün öncesi bir tarih seçiniz.",
        'newjconrequestmaterials':
        "Anlaşmalı taraf için malzeme talep ediyorsunuz.Teslim alınan malzemeler LM üzerine zimmetlenecektir.",
        'created': "Oluşturuldu",
        'createdby': "Oluşturan",
        'selectarecord':
        "Bu eylemi gerçekleştirmeden önce bir kayıt seçmelisiniz.",
        'selectasystemtocreateuser':
        "Lütfen kullanıcı oluşturmak için bir sistem seçiniz.",
        'comments': "Yorumlar",
        'newpurchaseorder': "Satın Alma Emri Oluştur",
        'newpurchaseorderrequisition': "Satın Alma Talebi Oluştur",
        'documents': "Dokumanlar",
        'customer': "Müşteri",
        'branch': "Şube",
        'download': "İndir",
        'details': "Detaylar",
        'filter': "Filtrele",
        'allday': "Tüm Gün",
        'checkall': "Tümünü Seç",
        'frequencyzerovalue': "Sıklık alanı 0 olamaz",
        'autocreationzerovalue': "Otomatik oluşturma zamanı 0 olamaz",
        'frequencyerr': "Yaklaşan görev hatırlatma zamanı sıklıktan büyük olamaz.",
        'trxtypecheck': "Lütfen önce işlem tipini seçiniz",
        'daterequested': "Bildirim zamanı gelecek zaman olamaz",
        'deadline': "İstenen tarih bildirim zamanından önce olamaz",
        'boodate01': "Çalışma tarihi gelecek zaman olamaz",
        'boodate02': "Bildirim zamanından önceye çalışma saati girilemez",
        'misccostdate': "Bildirim zamanından önce bir tarih seçilemez",
        'pastdate': "Geçmiş tarih seçilemez",
        'pptasknotselected': "Hakedişe dahil olacak en az bir adet görev kaydı seçmelisiniz.",
        'invpspnotselected': "Faturaya dahil olacak en az bir adet hakediş seçmelisiniz.",
        'potowarehousenotselected': "Depoya almak için en az bir adet kayıt seçmelisiniz.",
        'invlinenotselected': "Faturaya dahil edilecek en az bir satır seçmelisiniz.",
        'contractdelete': "Silmek için en az bir satır seçmelisiniz.",
        'selectatask': "Lütfen bir görev seçiniz",
        'save': "Kaydet",
        'activitycompleted': "Seçilen aktivite tamamlanmış, planlama yapılamaz.",
        'misccostexch': "Seçilen tarih için kur bilgisi girilmemiş",
        'closedanddisabled': "Kayıt kapatıldığı için işlem yapılamaz",
        'actdurationdatecontrol': "Aktivite başlangıç ve bitişi belirtilmelidir",
        'pswdcomplexity': "Şifre alanı standartları karşılamıyor. Şifre en az 8 karakter uzunluğunda olmalıdır ve büyük harf, küçük harf, özel karakter (!@#$%^&*.), sayı içermelidir.",
        'fileisbeingprepared': "Talep edilen dosya işleniyor, lütfen bekleyiniz...",
        'ACTIVE': "Aktif",
        'COMPLETED': "Tamamlandı",
        'PAUSED': "Beklemede",
        'WAITING': "Müşteri Kaynaklı Beklemede",
        'pointcount': "Nokta Sayısı",
        'location': "Lokasyon",
        'continuing': "Devam Eden",
        'actcount': "Akt. Sayısı",
        'total': "Toplam",
        'totalcost': "Toplam Maliyet",
        'totalsales': "Toplam Satış",
        'lastaction': "Son İşlem",
        'showall': "Tümünü Göster",
        'statuschange': "Durum Değişikliği",
        'dayoffrequesttypeinfo': "Seçilen izin tipi için kullanılabilecek maksimum süre : ",
        'chargingperiods': {
            'DAILY': "Günlük",
            'HOURLY': "Saatlik",
            'KM': "Kilometre"
        },
        'durationunit': {
            'DAY': "Gün",
            'HOUR': "Saat",
            'PCE': "Adet",
            'SET': "Set"
        },
        'activitystatuses': {
            'CALBAS': "Çalışma Başladı",
            'MSKBEK': "Müşteri Kaynaklı Bekleme",
            'NOTSTARTED': "Henüz Başlamadı",
            'CLSTAM': "Çalışma Tamamlandı",
            'MUSERT': "Müşteri Erteleme",
            'IZNGVN': "İzin / Güvenlik",
            'EKPDGS': "Ekip Değişikliği",
            'MSİBTM': "Mesai Bitimi",
            'PRCBEK': "Parça Bekliyor",
            'KESIF': "Keşif Tamamlandı"
        },
        'delete': "Sil",
        'list': "Liste",
        'uploadfileextensionerr': "Sadece .xlsx veya .xls uzantılı dosyalara izin verilir",
        'specifycancellationreason': "Lütfen iptal nedenini seçiniz",
        'calcmethod': {
            'CONTRACT' : "SÖZLEŞME",
            'PLANNEDPARTS': "TEKLİF",
            'CUSTOMERPRICES': "MÜŞTERİ",
            'PARTUNITSALESPRICE': "PARÇA",
            'PROGRESSPAYMENT': "EN SON",
            'AVERAGE': "ORTALAMA",
            'TASKPRICE': "ÖZEL FİYAT",
            'CUSTOMERPARTPRICES': "SÖZLEŞME",
            'QUOTATION': "TEKLİF"
        },
        'timekeepingitemstatus': {
            'R': "Açık",
            'WA': "Onay Bekliyor",
            'APP': "Onaylandı",
            'REJ': "Reddedildi"
        },
        'nottype': {
            "NEWCOMMENT": "Yorumlar",
            "NEWDOC": "Dokumanlar",
            "NEWTASK": "Görevler",
            "NEWTODO": "Yapılacaklar Listesi"
        },
        'unspecifieddoctype': "Belirsiz",
        'eqpcodelength': "Ekipman kodu {0} karakter olmalıdır.",
        'progresspaymentselectionerror': "Seçilen tüm hakediş kayıtlarının mevcut durumu aynı olmalıdır.",
        'progresspaymentinvoiceoptionserror': "Seçilen tüm hakediş kayıtlarının organizasyon ve müşterisi aynı olmalıdır.",
        'taskselectionerror': "Seçilen tüm görev kayıtlarının mevcut durumu aynı olmalıdır.",
        'misccosts': "Ek Maliyetler",
        'errinvoicedate': "Ayın 29'u ile son günü arasında fatura kaydı oluşturulamaz.",
        'subjectisempty': "Konu alanı boş olamaz!",
        'contentisempty': "İçerik alanı boş olamaz!",
        'toisempty': "Kime alanı boş olamaz!",
        'invalidemail': "Geçersiz e-posta adresi",
        'record': "Kayıt",
        'whasquotation': "Dikkat!<br/> Teklif var! ",
        'groupusers': "Kullanıcıları Grupla",
        'selecttradeoruser': "Lütfen ekip ya da kullanıcı(lar) seçiniz",
        'quotations': "Teklifler",
        'supervisions': "Denetlemeler",
        'purchaseorders': "Satın Alma Emirleri",
        'purchaseorderscannotbediff': "Satın Alma Emirleri farklı olamaz.",
        'purchaseorderrequisitions': "Satın Alma Talepleri",
        'quotationorder': "Bu teklif en düşük maliyet sıralamasına göre toplam {0} teklif arasında <span style=\"color: #fb8b8b;font-size: 3em;\">{1}</span>. sıradadır. Görev/Aktivite : {2}/{3}",
        'newquotation': "Teklif Oluştur",
        'newsupervision': "Denetleme Oluştur",
        'openlinkinnewwindow': "Yeni Pencerede Aç",
        'copytoclipboard': "Panoya Kopyala",
        'pleaseselect': "Lütfen Seçiniz",
        'trxtype': "Lütfen öncelikle işlem tipini seçiniz",
        'selectapart': "Lütfen öncelikle parça seçiniz",
        'selectawarehouse': "Lütfen öncelikle depo seçiniz",
        'checklisttypes': {
            'YESNO': "Evet/Hayır",
            'NUMERIC': "Nümerik",
            'DATE': "Tarih",
            'FREETEXT': "Düz Metin",
            'LOOKUP': "Çoktan Seçmeli",
            'CHECKBOX': "İşaretleme Kutusu",
            'BARCODE' : "Barkod"
        },
        'yes': "Evet",
        'no': "Hayır",
        'uploaderr': "Yükleme işlemi sırasında hatalarla oluştu.Lütfen hata listesini inceleyin.",
        'error': "Hata",
        'tcknerr': "T.C. Kimlik Numarası 11 Haneli Olmalıdır.",
        'partorequiperr': "Durum değişikliği yapılamaz. Lütfen öncelikle malzeme ve/veya ekipman seçimi yapınız.",
        'ignoreddayserr': "Haftanın tüm günleri seçilemez",
        'invoicerequiredfieldserr': "Lütfen Fatura No ve Fatura Tarihi alanlarını boş bırakmayınız.",
        'invalidphone': "Geçersiz Telefon Numarası",
        'erremptyrating': "Lütfen bir puanlama değeri seçiniz",
        'addtoWarehouse': "Depoya Al",
        'addtoWarehouseasList': "Tüm Parçaları Depoya Al",
        'refundFromWarehouse': "İade",
        'purchaseordererror': "Giriş/Çıkış Miktarı bekleyen miktarı geçemez.",
        'typeleveleeror': "Tip farklılığından dolayı güncelleme gerçekleştirilemedi.",
        'typetofilter': "Filtrelemek için yazınız.",
        'clearfilter': "Filtreyi temizle",
        'linedetails': "Satır Detayları",
        'editprices' : "Fiyatları Güncelle",
        'sent': "Gönderildi",
        'notsend': "Gönderilmedi",
        'totalpayment': "Toplam Hakediş",
        'clickherefornewquo': "Teklif oluşturmak için tıklayınız.",
        'clickforseequo': "Teklifleri görüntülemek için tıklayınız.",
        'sendforapproval': "Onaya Gönder",
        'alreadysent': "Onaya Gönderildi",
        'completeactivity': "Tamamla / Beklet",
        'alredycompleted': "Aktivite Tamamlandı",
        'countmustbegreaterthenzero': "Adet 0 dan büyük olmalı",
        'countmustbegreaterthenzero2': "Miktar 0 dan büyük olmalı",
        'pricemustbegreaterthenzero': "Birim fiyat 0 dan büyük olmalı",
        'discountmustbegreaterthenzero': "İskonto minmum 0 olmalı",
        'deliverytowarehouse': "Merkeze Teslimat",
        'deliverytocrew': "Ekibe veya Çözüm Ortağına Teslimat",
        'deliverytocustomer': "Müşteriye teslimat",
        'cannotupdateprice': "Bu fiyat tipi güncellenemez.",
        'sendback': "Geri Gönder",
        'quolines': "Teklif oluşturabilmek için satır eklemeniz gerekmektedir.",
        'quototask': "Teklifleri Göreve Kopyala",
        'returntotal': "İade Toplamı",
        'invtotal': "Fatura Toplamı",
        'returnhigherthanmax': "İade tutarı maximum tutarı geçemez.",
        'gototask': "Göreve git",
        'gotoequipment': "Ekipmana git",
        'activitycomplete': "Aktivite Tamamlandı",
        'estimationcompleted': "Keşif Tamamlandı",
        'warehousescannotbedifferent': "Depolar farklı olamaz.",
        'orgsscannotbedifferent': "Organizasyonlar farklı olamaz.",
        'partmodalinfo': "<i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\" /> <strong>Varsayılan olarak sözleşmeli parçalar listelenmektedir. Sağ üst bölümdeki filtre seçeneklerinden \"Tüm Parçalar\" seçilerek kayıtların tümü  görüntülenebilir.</strong>",
        'servicecodesmodalinfo': "<i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\" /> <strong>Varsayılan olarak sözleşmeli servis kodları listelenmektedir. Sağ üst bölümdeki filtre seçeneklerinden \"Tüm Servis Kodları\" seçilerek kayıtların tümü  görüntülenebilir.</strong>",
        'batchprogresstatus' : {
            "1" : "ÇALIŞIYOR",
            "2" : "KAYDEDİLİYOR",
            "3" : "TAMAMLANDI"        
        },
        'customerselectionerr': "Müşteri ve/veya müşteri grubu seçilmelidir.",
        'invalidlicenseplate': "Plaka formatı hatalı.",
        'invalidyear': "Geçersiz Yıl",
        'birthdateerr': "Doğum tarihi gelecek tarihli olamaz",
        'licenseissuedateerr': "Ehliyet veriliş tarihi gelecek tarihli olamaz",
        'lastgraduateddateerr' : "Mezuniyet tarihi gelecek tarihli olamaz",
        'invalidemail': "E-Posta alanı geçersiz değer içeriyor.",
        'details': "Firma Bilgileri",
        'doccount': "Dokuman Sayısı",
        'invalidfiletype': "Geçersiz dosya tipi",
        'warehouse': "Depo",
        'inventoryreceiptstatuses': {
            "N": "Yeni",
            "WA": "Onay Bekliyor",
            "APP": "Onaylandı",
            "RET" : "İade Edildi"
        },
        'column': "Sütun",
        'columntitle': "Sütun Başlığı",
        'tables': "Tablolar",
        'screenexists': "Ekran daha Önce oluşturulmuştur",
        'review': "Değerlendir",
        'seen': "Görüldü",
        'adminguide': "Yönetici Klavuzu",
        'enduserguide': "Kullanıcı Klavuzu",
        'ok': "Tamam",
        'user': "Kullanıcı",
        'admin': "Yönetici",
        'fullscreen': "Tam Ekran",
        'guide': "Klavuz",
        'setasprimary': "Birincil Olarak Belirle",
        'imgtyperequired': "Geçersiz dosya tipi. Lütfen bir görsel ekleyiniz.",
        'contactinfo': "İletişim Bilgileri",
        'imgtyperequired': "Geçersiz dosya tipi. Lütfen bir görsel ekleyiniz.",
        'createpo': "SE Oluştur",
        'multiplewrhselected': "Seçilen Taleplerin Depoları Aynı Olmak Zorunda.",
        'prqdetails': 'Satın Alma Talebi Detayları',
        'reqlinenotselected': "Satın Alma Emrine Dahil Edilecek En Az Bir Satır Seçilmelidir.",
        'tsacompleted': "Tamamlanmış bir aktivite için teklif oluşturamazsınız. Lütfen sistem yöneticiniz ile iletişime geçiniz ve yeni bir aktivite üzerinden teklif oluşturunuz.",
        'cuspm': "Müşteri Yöneticisi",
        'regresp': "Bölge Yöneticisi",
        'supplier': "Çözüm Ortağı",
        'address': "Şube/Mağaza Adresi",      
        'daterange': "Tarih Aralığı",
        'signature': "İmza",
        'matchbyprovince': "İle göre eşle",
        'matchbycounty': "İlçeye göre eşle",
        'matchbycategory': "Türe göre eşle",
        'matchbyregion': "Bölgeye göre eşle",
        'cusgetallinfo': "En fazla tutarlı 20 hakedişin gelmesi için işaretlemeyiniz.",
        'similarrecordfound': "Dikkat! İlgili şube için aynı tip ve kategoride açık bir görev var.",
        'selectpriorityfirst': "Lütfen öncelik alanını seçiniz.",
        'setprofitmargin': "Kâr Oranı Belirle",
        'opentherecord': "Kaydı Aç"


    }
};
var customstrings = {
    EN: {
        'shaya_err001': "Shaya / Starbucks görevlerini kapatmadan önce Fatura Tipi, Hakediş Yılı, Hakediş Ayı alanlarının doldurulması zorunludur. "
    },
    TR: {
        'shaya_err001': "Shaya / Starbucks görevlerini kapatmadan önce Fatura Tipi, Hakediş Yılı, Hakediş Ayı alanlarının doldurulması zorunludur. "
    }
}