//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Reports.PSP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportPspStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportPspStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ovi.Task.UI.Resources.Views.Reports.PSP.ReportPspStrings", typeof(ReportPspStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string authorized {
            get {
                return ResourceManager.GetString("authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string branch {
            get {
                return ResourceManager.GetString("branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Type.
        /// </summary>
        public static string branchtype {
            get {
                return ResourceManager.GetString("branchtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string docs {
            get {
                return ResourceManager.GetString("docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show params.
        /// </summary>
        public static string donotshowparams {
            get {
                return ResourceManager.GetString("donotshowparams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format 1.
        /// </summary>
        public static string format1 {
            get {
                return ResourceManager.GetString("format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format 2.
        /// </summary>
        public static string format2 {
            get {
                return ResourceManager.GetString("format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format 3.
        /// </summary>
        public static string format3 {
            get {
                return ResourceManager.GetString("format3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format 4.
        /// </summary>
        public static string format4 {
            get {
                return ResourceManager.GetString("format4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaya.
        /// </summary>
        public static string format5 {
            get {
                return ResourceManager.GetString("format5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        public static string groupcode {
            get {
                return ResourceManager.GetString("groupcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Has Quotation?.
        /// </summary>
        public static string hasquotation {
            get {
                return ResourceManager.GetString("hasquotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide lines valued zero.
        /// </summary>
        public static string hidezero {
            get {
                return ResourceManager.GetString("hidezero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Table.
        /// </summary>
        public static string includetable {
            get {
                return ResourceManager.GetString("includetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string invoicedate {
            get {
                return ResourceManager.GetString("invoicedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string invoiceno {
            get {
                return ResourceManager.GetString("invoiceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Service Forms.
        /// </summary>
        public static string onlyserviceforms {
            get {
                return ResourceManager.GetString("onlyserviceforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        public static string outputtype {
            get {
                return ResourceManager.GetString("outputtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Payment No.
        /// </summary>
        public static string pspcode {
            get {
                return ResourceManager.GetString("pspcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress payment date.
        /// </summary>
        public static string pspdate {
            get {
                return ResourceManager.GetString("pspdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Payment Status.
        /// </summary>
        public static string pspstatus {
            get {
                return ResourceManager.GetString("pspstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string reportformat {
            get {
                return ResourceManager.GetString("reportformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaya / Starbucks.
        /// </summary>
        public static string shaya {
            get {
                return ResourceManager.GetString("shaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tipi (Shaya).
        /// </summary>
        public static string shaya_ftip {
            get {
                return ResourceManager.GetString("shaya_ftip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakediş Ayı (Shaya).
        /// </summary>
        public static string shaya_hay {
            get {
                return ResourceManager.GetString("shaya_hay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakediş Yılı (Shaya).
        /// </summary>
        public static string shaya_hyil {
            get {
                return ResourceManager.GetString("shaya_hyil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task No.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Category.
        /// </summary>
        public static string taskcategory {
            get {
                return ResourceManager.GetString("taskcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Completed.
        /// </summary>
        public static string taskcompleted {
            get {
                return ResourceManager.GetString("taskcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string tasktype {
            get {
                return ResourceManager.GetString("tasktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Payment Report.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        public static string tsktasktype {
            get {
                return ResourceManager.GetString("tsktasktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string xls {
            get {
                return ResourceManager.GetString("xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
